
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 12;
  public static final int MULT = 26;
  public static final int PARENTESIS_CIERRE = 7;
  public static final int CHAR = 15;
  public static final int CONCAT = 31;
  public static final int DEFINIR_GLOBALES = 48;
  public static final int ENTERO = 20;
  public static final int CASE = 42;
  public static final int DOUBLE = 14;
  public static final int INT = 13;
  public static final int FOR = 44;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int ELSEIF = 37;
  public static final int IGUAL = 19;
  public static final int OR = 33;
  public static final int INCREMENTO = 45;
  public static final int SUMA = 24;
  public static final int MAIN = 2;
  public static final int IF = 18;
  public static final int UMENOS = 28;
  public static final int PTOCOMA = 21;
  public static final int EOF = 0;
  public static final int BOOLEAN = 16;
  public static final int DECIMAL = 23;
  public static final int error = 1;
  public static final int T_F = 29;
  public static final int COMA = 51;
  public static final int CADENA = 30;
  public static final int MENOS = 25;
  public static final int MAYOR_QUE = 35;
  public static final int BREAK = 43;
  public static final int VOID = 4;
  public static final int SWITCH = 40;
  public static final int DOBLE_IGUAL = 11;
  public static final int DOSPTOS = 39;
  public static final int LLAVE_ABERTURA = 3;
  public static final int ELSE = 38;
  public static final int VARIABLE = 22;
  public static final int WHILE = 46;
  public static final int DEFAULT = 41;
  public static final int MAYOR_IGUAL = 9;
  public static final int PARENTESIS_ABERTURA = 6;
  public static final int LLAVE_CIERRE = 8;
  public static final int STRING = 17;
  public static final int MENOR_QUE = 36;
  public static final int NEWVALOR = 50;
  public static final int MENOR_IGUAL = 10;
  public static final int DIVISION = 27;
  public static final int DOLAR = 49;
  public static final int DO = 47;
  public static final int PRINT = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "LLAVE_ABERTURA",
  "VOID",
  "PRINT",
  "PARENTESIS_ABERTURA",
  "PARENTESIS_CIERRE",
  "LLAVE_CIERRE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "DOBLE_IGUAL",
  "DISTINTO",
  "INT",
  "DOUBLE",
  "CHAR",
  "BOOLEAN",
  "STRING",
  "IF",
  "IGUAL",
  "ENTERO",
  "PTOCOMA",
  "VARIABLE",
  "DECIMAL",
  "SUMA",
  "MENOS",
  "MULT",
  "DIVISION",
  "UMENOS",
  "T_F",
  "CADENA",
  "CONCAT",
  "AND",
  "OR",
  "NOT",
  "MAYOR_QUE",
  "MENOR_QUE",
  "ELSEIF",
  "ELSE",
  "DOSPTOS",
  "SWITCH",
  "DEFAULT",
  "CASE",
  "BREAK",
  "FOR",
  "INCREMENTO",
  "WHILE",
  "DO",
  "DEFINIR_GLOBALES",
  "DOLAR",
  "NEWVALOR",
  "COMA"
  };
}

